# Generated by Django 5.2.9 on 2025-12-22 22:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Mailing",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_at", models.DateTimeField(verbose_name="Дата и время начала")),
                ("end_at", models.DateTimeField(verbose_name="Дата и время окончания")),
                (
                    "status",
                    models.CharField(
                        choices=[("CREATED", "Создана"), ("LAUNCHED", "Запущена"), ("COMPLETED", "Завершена")],
                        default="CREATED",
                        max_length=10,
                        verbose_name="Статус рассылки",
                    ),
                ),
            ],
            options={
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
                "ordering": ["start_at"],
                "permissions": [
                    ("can_send_mailing", "Can send mailing"),
                    ("can_disabling_mailing", "Can disabling mailing"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=150, verbose_name="Тема письма")),
                ("content", models.TextField(blank=True, null=True, verbose_name="Тело письма")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Дата изменения")),
            ],
            options={
                "verbose_name": "сообщение",
                "verbose_name_plural": "сообщения",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Recipients",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, verbose_name="Почта")),
                ("full_name", models.CharField(max_length=150, verbose_name="Полное имя получателя")),
                ("comment", models.TextField(blank=True, null=True, verbose_name="Комментарии")),
            ],
            options={
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
                "ordering": ["email"],
            },
        ),
        migrations.CreateModel(
            name="MailingAttempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("attempt_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата и время попытки")),
                (
                    "status",
                    models.CharField(
                        choices=[("SUCCESS", "Успешно"), ("FAILED", "Не успешно")],
                        max_length=10,
                        verbose_name="Статус рассылки",
                    ),
                ),
                ("response", models.TextField(blank=True, null=True, verbose_name="Ответ почтового сервера")),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mailing.mailing", verbose_name="Рассылка"
                    ),
                ),
            ],
            options={
                "verbose_name": "попытка",
                "verbose_name_plural": "попытки",
                "ordering": ["attempt_at"],
            },
        ),
    ]
