# Generated by Django 5.2.9 on 2025-12-10 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="recipients",
            name="mailer",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Отправитель",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="recipients",
            name="email",
            field=models.EmailField(max_length=254, verbose_name="Почта"),
        ),
    ]
