# Generated by Django 5.2.9 on 2025-12-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="is_disabled",
            field=models.BooleanField(default=False, verbose_name="Блокировка рассылки"),
        ),
    ]
