# Generated by Django 5.2.9 on 2025-12-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_recipients_mailer_alter_recipients_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="end_at",
            field=models.DateTimeField(verbose_name="Дата и время окончания"),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="start_at",
            field=models.DateTimeField(verbose_name="Дата и время начала"),
        ),
    ]
